# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\"5\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0f\n\x07payload\x18\x03 \x01(\t\"/\n\rEventResponse\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0f\n\x07payload\x18\x02 \x01(\t2-\n\x06\x45vents\x12#\n\tSendEvent\x12\x06.Event\x1a\x0e.EventResponseB\x0f\xaa\x02\x0c\x66urnace.grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014furnace.grpc'
  _globals['_EVENT']._serialized_start=15
  _globals['_EVENT']._serialized_end=68
  _globals['_EVENTRESPONSE']._serialized_start=70
  _globals['_EVENTRESPONSE']._serialized_end=117
  _globals['_EVENTS']._serialized_start=119
  _globals['_EVENTS']._serialized_end=164
# @@protoc_insertion_point(module_scope)
