# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\"%\n\x05\x46rame\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x0f\n\x07payload\x18\x02 \x01(\t2-\n\rStreamService\x12\x1c\n\x06Stream\x12\x06.Frame\x1a\x06.Frame(\x01\x30\x01\x42\x0f\xaa\x02\x0c\x66urnace.grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014furnace.grpc'
  _globals['_FRAME']._serialized_start=16
  _globals['_FRAME']._serialized_end=53
  _globals['_STREAMSERVICE']._serialized_start=55
  _globals['_STREAMSERVICE']._serialized_end=100
# @@protoc_insertion_point(module_scope)
